/*
 * @FileName:: 
 * @Author: 
 * @Date: 2022-05-10 19:16:54
 * @LastEditTime: 2022-05-20 15:55:47
 * @Description: 
 */
#ifndef __CIAS_QCLOUD_DEV_H__
#define __CIAS_QCLOUD_DEV_H__
#include "cias_demo_config.h"
/* #define QCLOUD_IOT_PRODUCT_ID  "TV5DGH8IHX"
#define QCLOUD_IOT_DEV_NAME "TANMI_P1_000000000002"
#define QCLOUD_IOT_DEV_SECRET "x3Fz4v19r0C2yXdTDL5p8Q==" */
//#define QCLOUD_IOT_DEV_MAC ""

//add by houwang
#define ACCOUNT_BELONG_YUAN_XIAO_PIN   0
#define ACCOUNT_BELONG_WU_HONG_CHUAN   1
#define ACCOUNT_BELONG_HOU_WANG        0

#if ACCOUNT_BELONG_YUAN_XIAO_PIN
#define YXP_ACCOUNT_FOR_YJD     0
#define YXP_ACCOUNT_FOR_WHC     0
#define YXP_ACCOUNT_FOR_HW      0
#endif//ACCOUNT_BELONG_YUAN_XIAO_PIN

#if ACCOUNT_BELONG_WU_HONG_CHUAN
#define WHC_ACCOUNT_FOR_HW_1      0
#define WHC_ACCOUNT_FOR_HW_2      0
#define WHC_ACCOUNT_FOR_HW_3      0
#define WHC_ACCOUNT_FOR_HW_4      0
#define WHC_ACCOUNT_FOR_HW_5      1
#define WHC_ACCOUNT_FOR_HW_6      0
#define WHC_ACCOUNT_FOR_HW_7      0
#define WHC_ACCOUNT_FOR_HW_8      0
#endif//ACCOUNT_BELONG_WU_HONG_CHUAN

#if ACCOUNT_BELONG_HOU_WANG
#define HW_ACCOUNT_FOR_DEBUG            0
#define HW_ACCOUNT_FOR_LIGHT_DEMO_1     1
#define HW_ACCOUNT_FOR_LIGHT_DEMO_2     0
#define HW_ACCOUNT_FOR_LIGHT_DEMO_3     0
#define HW_ACCOUNT_FOR_LIGHT_DEMO_4     0
#define HW_ACCOUNT_FOR_LIGHT_DEMO_5     0
#define HW_ACCOUNT_FOR_LIGHT_DEMO_6     0
#define HW_ACCOUNT_FOR_LIGHT_DEMO_7     0
#define HW_ACCOUNT_FOR_LIGHT_DEMO_8     0
#define HW_ACCOUNT_FOR_LIGHT_DEMO_9     0
#endif//ACCOUNT_BELONG_HOU_WANG

//add by whc 标准智能管家 三元组信息注意不能同时使用

#if ACCOUNT_BELONG_YUAN_XIAO_PIN && YXP_ACCOUNT_FOR_YJD
#define QCLOUD_IOT_PRODUCT_ID   "ZDFVDMWJWB" //yu
#define QCLOUD_IOT_DEV_NAME     "D001"
#define QCLOUD_IOT_DEV_SECRET   "5HUFKQvurC5OGrXAw9+fCw==" 
#endif

#if ACCOUNT_BELONG_YUAN_XIAO_PIN && YXP_ACCOUNT_FOR_HW
#define QCLOUD_IOT_PRODUCT_ID   "ZDFVDMWJWB"  //hou  子账号
#define QCLOUD_IOT_DEV_NAME     "D002"
#define QCLOUD_IOT_DEV_SECRET   "ov6NNcDYXZABFd4p0iWBAQ=="
#endif

#if ACCOUNT_BELONG_YUAN_XIAO_PIN && YXP_ACCOUNT_FOR_WHC
#define QCLOUD_IOT_PRODUCT_ID   "ZDFVDMWJWB" //wu
#define QCLOUD_IOT_DEV_NAME     "D018"
#define QCLOUD_IOT_DEV_SECRET   "M72NVN9rzCiQn6UQ5XdYSg=="

// #define QCLOUD_IOT_PRODUCT_ID   "ZDFVDMWJWB"
// #define QCLOUD_IOT_DEV_NAME     "D004"
// #define QCLOUD_IOT_DEV_SECRET   "S0DiDGCcybGxjuGM78tz+g==" 
#endif

#if ACCOUNT_BELONG_WU_HONG_CHUAN && WHC_ACCOUNT_FOR_HW_1
#define QCLOUD_IOT_PRODUCT_ID   "Z19E12UBTV" //hou 子账号
#define QCLOUD_IOT_DEV_NAME     "dev_0001"
#define QCLOUD_IOT_DEV_SECRET   "Hw7H69cXj5U0qoMPg5GJmw=="
#endif

#if ACCOUNT_BELONG_WU_HONG_CHUAN && WHC_ACCOUNT_FOR_HW_2
#define QCLOUD_IOT_PRODUCT_ID   "Z19E12UBTV" //hou 子账号
#define QCLOUD_IOT_DEV_NAME     "dev_0002"
#define QCLOUD_IOT_DEV_SECRET   "PcE+rH4/67+AbH5jG7bdWQ=="
#endif

#if ACCOUNT_BELONG_WU_HONG_CHUAN && WHC_ACCOUNT_FOR_HW_3
#define QCLOUD_IOT_PRODUCT_ID   "Z19E12UBTV" //hou 子账号
#define QCLOUD_IOT_DEV_NAME     "dev_0003"
#define QCLOUD_IOT_DEV_SECRET   "cBNCg3HHFd+CUGWOJba6JQ=="
#endif

#if ACCOUNT_BELONG_WU_HONG_CHUAN && WHC_ACCOUNT_FOR_HW_4
#define QCLOUD_IOT_PRODUCT_ID   "Z19E12UBTV" //hou 子账号
#define QCLOUD_IOT_DEV_NAME     "dev_0004"
#define QCLOUD_IOT_DEV_SECRET   "5xa4BsMamEsgi9tIH1A/iw=="
#endif

#if ACCOUNT_BELONG_WU_HONG_CHUAN && WHC_ACCOUNT_FOR_HW_5
#define QCLOUD_IOT_PRODUCT_ID   "Z19E12UBTV" //hou 子账号
#define QCLOUD_IOT_DEV_NAME     "dev_0005"
#define QCLOUD_IOT_DEV_SECRET   "/4nHK3VxpgOuG39hGDRusg=="
#endif

#if ACCOUNT_BELONG_WU_HONG_CHUAN && WHC_ACCOUNT_FOR_HW_6
#define QCLOUD_IOT_PRODUCT_ID   "Z19E12UBTV" //hou 子账号
#define QCLOUD_IOT_DEV_NAME     "dev_0006"
#define QCLOUD_IOT_DEV_SECRET   "FywWMrAXTYmd8X7ecrM0Bg=="
#endif

#if ACCOUNT_BELONG_WU_HONG_CHUAN && WHC_ACCOUNT_FOR_HW_7
#define QCLOUD_IOT_PRODUCT_ID   "Z19E12UBTV" //hou 子账号
#define QCLOUD_IOT_DEV_NAME     "dev_0007"
#define QCLOUD_IOT_DEV_SECRET   "yf+OxDthODAKU3ji1eShaA=="
#endif

#if ACCOUNT_BELONG_WU_HONG_CHUAN && WHC_ACCOUNT_FOR_HW_8
#define QCLOUD_IOT_PRODUCT_ID   "Z19E12UBTV" //hou 子账号
#define QCLOUD_IOT_DEV_NAME     "dev_0008"
#define QCLOUD_IOT_DEV_SECRET   "NlP1aV3kQ2DOUYnGPqHVEg=="
#endif

#if ACCOUNT_BELONG_HOU_WANG && HW_ACCOUNT_FOR_LIGHT_DEMO_1
#define QCLOUD_IOT_PRODUCT_ID   "E9PJAE5K3I"    //hou 个人账号
#define QCLOUD_IOT_DEV_NAME     "dev_01"
#define QCLOUD_IOT_DEV_SECRET   "brKkQ7hQB6kpNzOCLCrGOQ=="
#endif

#if ACCOUNT_BELONG_HOU_WANG && HW_ACCOUNT_FOR_LIGHT_DEMO_3
#define QCLOUD_IOT_PRODUCT_ID   "E9PJAE5K3I"    //hou 个人账号
#define QCLOUD_IOT_DEV_NAME     "dev_03"
#define QCLOUD_IOT_DEV_SECRET   "7euev8hNzuUnyj5QKzY/iw=="
#endif


#endif   //__CIAS_QCLOUD_DEV_H__