#include "system_msg_deal.h"
#include "ci130x_it.h"

#define BLE_APP_VER0    0x00
#define BLE_APP_VER1    0x01


#define BLE_APP_STATE_HEADER0      0x0
#define BLE_APP_STATE_HEADER1      0x1
#define BLE_APP_STATE_VER      0x2
#define BLE_APP_STATE_CMD     0x03
#define BLE_APP_STATE_DATA1    0x04
#define BLE_APP_STATE_DATA2     0x05
#define BLE_APP_STATE_CHECK_SUM      0x06
#define BLE_APP_STATE_END      0x07

#define BLE_APP_HEAD0			  	0xAA
#define BLE_APP_HEAD1			  	0xAE
#define BLE_APP_END        0xFB




typedef enum
{
	TEA_MACHINE_HEATING_TEMPRATURE_45_ONOFF = 0x08,
	TEA_MACHINE_HEATING_TEMPRATURE_65_ONOFF,
	TEA_MACHINE_HEATING_TEMPRATURE_85_ONOFF,
	TEA_MACHINE_HEATING_TEMPRATURE_100_ONOFF,
	TEA_MACHINE_AUTO_HEATING_ONOFF,
	TEA_MACHINE_REFRIGERATION_ONOFF = 0x0E, //start 
	TEA_MACHINE_OPEN_SCREEN = 0x12, //start 
	TEA_MACHINE_CLOSE_SCREEN , //start 
	TEA_MACHINE_OPEN_BOIL_TEA, //start 
	TEA_MACHINE_CLOSE_BOIL_TEA, //start 
	TEA_MACHINE_OPEN_BUBBLE_MILE, //start 
	TEA_MACHINE_CLOSE_BUBBLE_MILE, //start 
	TEA_MACHINE_OPEN_BOIL_COFFE, //start 
	TEA_MACHINE_CLOSE_BOIL_COFFE, //start 
	TEA_MACHINE_ONOFF = 0x81, //start 
	TEA_MACHINE_HEATING_ONOFF = 0x82	    , 
	TEA_MACHINE_KEEP_WARM_ONOFF = 0x84	    , 
	TEA_MACHINE_ADJUST_TEMPRATURE_DATA  =0x88,	
	TEA_MACHINE_ADD_ICE_WATER_ONOFF = 0x90,	
	TEA_MACHINE_ADD_WATER_ONOFF = 0xC3	    ,  
	TEA_MACHINE_BLE_CONNECT_ONOFF  =0xE0,	
	TEA_MACHINE_END       ,      //--end
}TEA_MACHINE_TO_VOICE_ID;
void app_deal_msg(sys_app_data_t *app_data);
void Init_ble_Paramter_If(void);
