Name: "libspeex"

Src:
    - bits.c
    - cb_search.c
    - exc_10_16_table.c
    - exc_10_32_table.c
    - exc_20_32_table.c
    - exc_5_256_table.c
    - exc_5_64_table.c
    - exc_8_128_table.c
    - filters.c
    - gain_table.c
    - gain_table_lbr.c
    - hexc_10_32_table.c
    - hexc_table.c
    - high_lsp_tables.c
    - kiss_fft.c
    - kiss_fftr.c
    - lpc.c
    - lsp.c
    - lsp_tables_nb.c
    - ltp.c
    - modes.c
    - modes_wb.c
    - nb_celp.c
    - quant_lsp.c
    - sb_celp.c
    - smallft.c
    - speex.c
    - speex_callbacks.c
    - speex_header.c
    - stereo.c
    - vbr.c
    - vorbis_psy.c
    - vq.c
    - window.c

Inc:
    - quant_lsp_bfin.h    
    - arch.h
    - os_support.h
    - quant_lsp.h
    - bfin.h
    - sb_celp.h
    - smallft.h
    - stack_alloc.h
    - nb_celp.h
    - ltp.h
    - ltp_arm4.h
    - ltp_bfin.h
    - ltp_sse.h
    - math_approx.h
    - misc_bfin.h
    - vbr.h
    - vorbis_psy.h
    - vq.h
    - vq_arm4.h
    - vq_bfin.h
    - vq_sse.h
    - _kiss_fft_guts.h
    - lpc.h
    - lpc_bfin.h    
    - kiss_fft.h
    - kiss_fftr.h
    - lsp.h
    - fftwrap.h
    - modes.h
    - lsp_bfin.h    
    - filters.h
    - filters_arm4.h
    - filters_bfin.h
    - filters_sse.h
    - fixed_arm4.h
    - fixed_arm5e.h    
    - cb_search.h
    - cb_search_sse.h
    - cb_search_arm4.h
    - cb_search_bfin.h
    - fixed_bfin.h
    - fixed_debug.h
    - fixed_generic.h
